# nvfetcher.toml
[broker]
src.github = "zeek/broker"
fetch.github = "zeek/broker"
git.fetchSubmodules = true

[clx]
src.github = "rapidsai/clx"
fetch.github = "rapidsai/clx"

[cnmem]
src.github = "NVIDIA/cnmem"
fetch.github = "NVIDIA/cnmem"

#Python Packages
[btest]
src.pypi = "btest"
fetch.pypi = "btest"



#Go Pkgs
# [deepsea]
# src.manual= "b48e9302d079ed9f53a9123a805096a845d2c6a5"
# fetch.github = "dsnezhkov/deepsea:b48e9302d079ed9f53a9123a805096a845d2c6a5"
