# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  broker = {
    pname = "broker";
    version = "v2.0.1";
    src = fetchgit {
      url = "https://github.com/zeek/broker";
      rev = "v2.0.1";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "19isnl3isnb8xinx7jsy9013psgr1jrnyspm3fpnsdn6q60igwdm";
    };
  };
  btest = {
    pname = "btest";
    version = "0.68";
    src = fetchurl {
      sha256 = "00nxf7rh38hrzjq4v70idbrjsgxd5nh97cj0k4qw4z0yl2l2s553";
      url = "https://pypi.io/packages/source/b/btest/btest-0.68.tar.gz";
    };
  };
  clx = {
    pname = "clx";
    version = "v0.19.0";
    src = fetchgit {
      url = "https://github.com/rapidsai/clx";
      rev = "v0.19.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1ka81kfzkpr37wc3qbma3qcavhd6rz2hc4n6sanj13fx76bpbs36";
    };
  };
  cnmem = {
    pname = "cnmem";
    version = "37896cc9bfc6536a8c878a1e675835c22d827821";
    src = fetchgit {
      url = "https://github.com/NVIDIA/cnmem";
      rev = "37896cc9bfc6536a8c878a1e675835c22d827821";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0wx25vn9dq0wwp1klx862cavsgf0f2b5m0sc1d2jr121v24z96jy";
    };
  };
  spicy = {
    pname = "spicy";
    version = "v1.1.0";
    src = fetchgit {
      url = "https://github.com/zeek/spicy";
      rev = "v1.1.0";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0vqnj9slgzxbcfrlfqd90dqya000ym0vkp3rrrsfr8zbdsj6ffi7";
    };
  };
}
