# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  spicy = {
    pname = "spicy";
    version = "v1.1.0";
    src = fetchgit {
      url = "https://github.com/zeek/spicy";
      rev = "v1.1.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "06dyk84gbiyva0iqpqcpzbklij3848m37al1zzpr46z3j95fdkd2";
    };
  };
}