# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  spicy = {
    pname = "spicy";
    version = "v1.1.0";
    src = fetchgit {
      url = "https://github.com/zeek/spicy";
      rev = "v1.1.0";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0vqnj9slgzxbcfrlfqd90dqya000ym0vkp3rrrsfr8zbdsj6ffi7";
    };
  };
  zeek = {
    pname = "zeek";
    version = "v2.0.1";
    src = fetchgit {
      url = "https://github.com/zeek/broker";
      rev = "v2.0.1";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "19isnl3isnb8xinx7jsy9013psgr1jrnyspm3fpnsdn6q60igwdm";
    };
  };
}
