# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  broker = {
    pname = "broker";
    version = "v2.0.1";
    src = fetchgit {
      url = "https://github.com/zeek/broker";
      rev = "v2.0.1";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "19isnl3isnb8xinx7jsy9013psgr1jrnyspm3fpnsdn6q60igwdm";
    };

  };
  btest = {
    pname = "btest";
    version = "0.68";
    src = fetchurl {
      sha256 = "00nxf7rh38hrzjq4v70idbrjsgxd5nh97cj0k4qw4z0yl2l2s553";
      url = "https://pypi.io/packages/source/b/btest/btest-0.68.tar.gz";
    };

  };
  choochoo = {
    pname = "choochoo";
    version = "bd5f7ed75c53977183249e9bad7bf094accd151f";
    src = fetchgit {
      url = "https://github.com/andrewcooke/choochoo";
      rev = "bd5f7ed75c53977183249e9bad7bf094accd151f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0az90ay6sn5r0lsd0zkka92vsrx1iif24nyrfgdzb6n9kqhaa45z";
    };

  };
  clx = {
    pname = "clx";
    version = "v21.06.00";
    src = fetchgit {
      url = "https://github.com/rapidsai/clx";
      rev = "v21.06.00";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1rj2r6wnk90svqmhrwvd9z94sg8sh7zvdqan3bp38d67chlaimjs";
    };

  };
  elastalert2 = {
    pname = "elastalert2";
    version = "2.1.1";
    src = fetchgit {
      url = "https://github.com/jertel/elastalert2";
      rev = "2.1.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0pqarwjjh6lnz40a7maxc2k31vb01pyfks9w35bv9zla422gfmfh";
    };

  };
  fastai = {
    pname = "fastai";
    version = "08a639548fd82ff22b7a72db9519f82b176511d7";
    src = fetchgit {
      url = "https://github.com/fastai/fastai";
      rev = "08a639548fd82ff22b7a72db9519f82b176511d7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0j5dpzr81mi6353n4nsd4s2hkpsmmrlhjkp8gs5vjr0g13z8hxm5";
    };

  };
  fastcore = {
    pname = "fastcore";
    version = "ae8148c85a0c57cc7fd6aa29fa13bdbfbe59be22";
    src = fetchgit {
      url = "https://github.com/fastai/fastcore";
      rev = "ae8148c85a0c57cc7fd6aa29fa13bdbfbe59be22";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1gpvbshywbf2di5hkrmjmh8s8z160p4hljsbxsblg1y77i5nsdvw";
    };

  };
  fastprogress = {
    pname = "fastprogress";
    version = "1.0.0";
    src = fetchurl {
      sha256 = "1zhv37q6jkqd1pfhlkd4yzrc3dg83vyksgzf32mjlhd5sb0qmql9";
      url = "https://pypi.io/packages/source/f/fastprogress/fastprogress-1.0.0.tar.gz";
    };

  };
  nvdtools = {
    pname = "nvdtools";
    version = "c3579d012178c462a53f4e2d1397a83c10c149df";
    src = fetchgit {
      url = "https://github.com/facebookincubator/nvdtools";
      rev = "c3579d012178c462a53f4e2d1397a83c10c149df";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1vczfn309vjsyw8kjxmf6fn3jvrw30hxzndr683lw377x52imd98";
    };

  };
  zed = {
    pname = "zed";
    version = "19d600933288c84965ce1b9ec28f02c411409f1d";
    src = fetchgit {
      url = "https://github.com/brimdata/zed";
      rev = "19d600933288c84965ce1b9ec28f02c411409f1d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "09ckj50pcxwggvhm7zs51lwxdf63byxifcgyjkllib2gqgn1xrn7";
    };

  };
}
