# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  broker = {
    pname = "broker";
    version = "ac0faa99f22a91310683d51f9c7b484ba874a309";
    src = fetchgit {
      url = "https://github.com/zeek/broker";
      rev = "ac0faa99f22a91310683d51f9c7b484ba874a309";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1hjicyp3h8nwxw3sh8xi8igj9zci1syvlbdyki5hk295k3nwsm3h";
    };

  };
  broker-to-json = {
    pname = "broker-to-json";
    version = "v_02";
    src = fetchgit {
      url = "https://github.com/grigorescu/broker-to-json";
      rev = "v_02";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1n0jklz0lhdkr29rjkhj9swmndvk152w5m90wdj2rrlg3lhrq4s9";
    };

  };
  btest = {
    pname = "btest";
    version = "0.68";
    src = fetchurl {
      sha256 = "00nxf7rh38hrzjq4v70idbrjsgxd5nh97cj0k4qw4z0yl2l2s553";
      url = "https://pypi.io/packages/source/b/btest/btest-0.68.tar.gz";
    };

  };
  choochoo = {
    pname = "choochoo";
    version = "bd5f7ed75c53977183249e9bad7bf094accd151f";
    src = fetchgit {
      url = "https://github.com/andrewcooke/choochoo";
      rev = "bd5f7ed75c53977183249e9bad7bf094accd151f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0az90ay6sn5r0lsd0zkka92vsrx1iif24nyrfgdzb6n9kqhaa45z";
    };

  };
  clx = {
    pname = "clx";
    version = "ca40fd4435cb85efd7196a96946817f0551ecc3a";
    src = fetchgit {
      url = "https://github.com/rapidsai/clx";
      rev = "ca40fd4435cb85efd7196a96946817f0551ecc3a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "14as9z700dy2f6qhzrcblws41aixb3q55bbjykqc63xc3k6yda7i";
    };

  };
  cnmem = {
    pname = "cnmem";
    version = "37896cc9bfc6536a8c878a1e675835c22d827821";
    src = fetchgit {
      url = "https://github.com/NVIDIA/cnmem";
      rev = "37896cc9bfc6536a8c878a1e675835c22d827821";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0wx25vn9dq0wwp1klx862cavsgf0f2b5m0sc1d2jr121v24z96jy";
    };

  };
  cudf = {
    pname = "cudf";
    version = "f0f2170972fd9f8c9570b95c9d84e4dbf714b3e3";
    src = fetchgit {
      url = "https://github.com/rapidsai/cudf";
      rev = "f0f2170972fd9f8c9570b95c9d84e4dbf714b3e3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "04l595wcp6r8p400ff36xwng9aknwnzaypyafx1ykfmdbhlsh4gr";
    };

  };
  durationpy = {
    pname = "durationpy";
    version = "0.5";
    src = fetchurl {
      sha256 = "022l9cqv648rxmavi1rgp2724jaynz7vwma6ycidfl3va9ml3yay";
      url = "https://pypi.io/packages/source/d/durationpy/durationpy-0.5.tar.gz";
    };

  };
  eZeeKonfigurator = {
    pname = "eZeeKonfigurator";
    version = "57c6faece572dbb7e4f45dc1e9c43952f1c392f0";
    src = fetchgit {
      url = "https://github.com/esnet/eZeeKonfigurator";
      rev = "57c6faece572dbb7e4f45dc1e9c43952f1c392f0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1vg2mmjwrnkird6w25phjgi4hbzs5wy27a8hv10br7j5izrf112a";
    };

  };
  eZeeKonfigurator_client = {
    pname = "eZeeKonfigurator_client";
    version = "efbe39bb1e40a0332d37c3291ee3c8af1ff7678e";
    src = fetchgit {
      url = "https://github.com/esnet/eZeeKonfigurator_client";
      rev = "efbe39bb1e40a0332d37c3291ee3c8af1ff7678e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0250aliybv54k7gv0y8fd9v4bpwyspzn8rz24108ijm8vfcjlr3g";
    };

  };
  elastalert2 = {
    pname = "elastalert2";
    version = "2.1.2";
    src = fetchgit {
      url = "https://github.com/jertel/elastalert2";
      rev = "2.1.2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0g7y2grfanl1b8v4xrnwnzrdw9zfj59wrxi60q535sy3501vs9qx";
    };

  };
  fastai = {
    pname = "fastai";
    version = "2af48aa4747c910283f679505bb5ef77a4b8eeec";
    src = fetchgit {
      url = "https://github.com/fastai/fastai";
      rev = "2af48aa4747c910283f679505bb5ef77a4b8eeec";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0bpjdz9cnzv5yg0qiibfmslwl306vrfxk70kpzzkvll8p21w3mni";
    };

  };
  fastcore = {
    pname = "fastcore";
    version = "ae8148c85a0c57cc7fd6aa29fa13bdbfbe59be22";
    src = fetchgit {
      url = "https://github.com/fastai/fastcore";
      rev = "ae8148c85a0c57cc7fd6aa29fa13bdbfbe59be22";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1gpvbshywbf2di5hkrmjmh8s8z160p4hljsbxsblg1y77i5nsdvw";
    };

  };
  fastprogress = {
    pname = "fastprogress";
    version = "1.0.0";
    src = fetchurl {
      sha256 = "1zhv37q6jkqd1pfhlkd4yzrc3dg83vyksgzf32mjlhd5sb0qmql9";
      url = "https://pypi.io/packages/source/f/fastprogress/fastprogress-1.0.0.tar.gz";
    };

  };
  nvdtools = {
    pname = "nvdtools";
    version = "952d0696a19961ffb4bc18c415df62ea4d00d2fa";
    src = fetchgit {
      url = "https://github.com/facebookincubator/nvdtools";
      rev = "952d0696a19961ffb4bc18c415df62ea4d00d2fa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "11cki0lhmjkh6cwbckgs0hy9qspgj7czxbv5w914d1k2r62a1wcc";
    };

  };
  rmm = {
    pname = "rmm";
    version = "eb2b9915a6e7209536ba2155bac8493e20784c19";
    src = fetchgit {
      url = "https://github.com/rapidsai/rmm";
      rev = "eb2b9915a6e7209536ba2155bac8493e20784c19";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1q5cz5pvk5vlmy76nw229k0bd9ddv735l2ymlqxlgkl6vz2qjfd4";
    };

  };
  sybilhunter = {
    pname = "sybilhunter";
    version = "2f0a8f09308f7de51ce1095353f4af82a8a15f88";
    src = fetchgit {
      url = "https://github.com/NullHypothesis/sybilhunter";
      rev = "2f0a8f09308f7de51ce1095353f4af82a8a15f88";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1gbvnalv98g366k2d0ziirqyi5psic3ga48qjdhyaslc1dns50xw";
    };

  };
  zat = {
    pname = "zat";
    version = "2924f5a713bb0c42dedbb89e031acab05b558e10";
    src = fetchgit {
      url = "https://github.com/SuperCowPowers/zat";
      rev = "2924f5a713bb0c42dedbb89e031acab05b558e10";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1k7jv07dv80cxsq1v087zb3q9li9gzxjn74lmb93xfs8sqk6lh03";
    };

  };
  zed = {
    pname = "zed";
    version = "ffb314b6bae5c53141995e74b83f138a3de9adce";
    src = fetchgit {
      url = "https://github.com/brimdata/zed";
      rev = "ffb314b6bae5c53141995e74b83f138a3de9adce";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1097s56fi8wq3ycbialrn520q3x53n81kl998l933w2qd0qrxnrp";
    };

  };
}
