# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  brim = {
    pname = "brim";
    version = "v0.24.0";
    src = fetchurl {
      sha256 = "1sj23gdcqyl9rkfr5dvr3bkswzcc0kyjlfv8633zal3h2dsb2xpl";
      url = "https://github.com/brimdata/brim/releases/download/v0.24.0/brim_amd64.deb";
    };

  };
  broker = {
    pname = "broker";
    version = "ea3e1c1aaf22f8a1918b13561ef33091a7312c29";
    src = fetchgit {
      url = "https://github.com/zeek/broker";
      rev = "ea3e1c1aaf22f8a1918b13561ef33091a7312c29";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1x7b0hk6y60bxlhmc8880997nhqb1cvgfhc0liidfn037px69yjk";
    };

  };
  broker-to-json = {
    pname = "broker-to-json";
    version = "v_02";
    src = fetchgit {
      url = "https://github.com/grigorescu/broker-to-json";
      rev = "v_02";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1n0jklz0lhdkr29rjkhj9swmndvk152w5m90wdj2rrlg3lhrq4s9";
    };

  };
  btest = {
    pname = "btest";
    version = "0.68";
    src = fetchurl {
      sha256 = "00nxf7rh38hrzjq4v70idbrjsgxd5nh97cj0k4qw4z0yl2l2s553";
      url = "https://pypi.io/packages/source/b/btest/btest-0.68.tar.gz";
    };

  };
  choochoo = {
    pname = "choochoo";
    version = "bd5f7ed75c53977183249e9bad7bf094accd151f";
    src = fetchgit {
      url = "https://github.com/andrewcooke/choochoo";
      rev = "bd5f7ed75c53977183249e9bad7bf094accd151f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0az90ay6sn5r0lsd0zkka92vsrx1iif24nyrfgdzb6n9kqhaa45z";
    };

  };
  clx = {
    pname = "clx";
    version = "668031e294bdc77ec056583d3cb4a77a4eae83c6";
    src = fetchgit {
      url = "https://github.com/rapidsai/clx";
      rev = "668031e294bdc77ec056583d3cb4a77a4eae83c6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0rrm9ikgimipjlwlnkwq0fbk3j42gzxy3s6xkz39jnm8vzx48883";
    };

  };
  cnmem = {
    pname = "cnmem";
    version = "37896cc9bfc6536a8c878a1e675835c22d827821";
    src = fetchgit {
      url = "https://github.com/NVIDIA/cnmem";
      rev = "37896cc9bfc6536a8c878a1e675835c22d827821";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0wx25vn9dq0wwp1klx862cavsgf0f2b5m0sc1d2jr121v24z96jy";
    };

  };
  cudf = {
    pname = "cudf";
    version = "b803c4ef48824238935f4972e472367d13ec34e7";
    src = fetchgit {
      url = "https://github.com/rapidsai/cudf";
      rev = "b803c4ef48824238935f4972e472367d13ec34e7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0f7j5dsah3ha23c2x0l6m96985pab9vd9icd1vj4yw50ixsaa296";
    };

  };
  durationpy = {
    pname = "durationpy";
    version = "0.5";
    src = fetchurl {
      sha256 = "022l9cqv648rxmavi1rgp2724jaynz7vwma6ycidfl3va9ml3yay";
      url = "https://pypi.io/packages/source/d/durationpy/durationpy-0.5.tar.gz";
    };

  };
  eZeeKonfigurator = {
    pname = "eZeeKonfigurator";
    version = "57c6faece572dbb7e4f45dc1e9c43952f1c392f0";
    src = fetchgit {
      url = "https://github.com/esnet/eZeeKonfigurator";
      rev = "57c6faece572dbb7e4f45dc1e9c43952f1c392f0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1vg2mmjwrnkird6w25phjgi4hbzs5wy27a8hv10br7j5izrf112a";
    };

  };
  eZeeKonfigurator_client = {
    pname = "eZeeKonfigurator_client";
    version = "efbe39bb1e40a0332d37c3291ee3c8af1ff7678e";
    src = fetchgit {
      url = "https://github.com/esnet/eZeeKonfigurator_client";
      rev = "efbe39bb1e40a0332d37c3291ee3c8af1ff7678e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0250aliybv54k7gv0y8fd9v4bpwyspzn8rz24108ijm8vfcjlr3g";
    };

  };
  elastalert2 = {
    pname = "elastalert2";
    version = "2.1.2";
    src = fetchgit {
      url = "https://github.com/jertel/elastalert2";
      rev = "2.1.2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0g7y2grfanl1b8v4xrnwnzrdw9zfj59wrxi60q535sy3501vs9qx";
    };

  };
  fastai = {
    pname = "fastai";
    version = "a9bdde89b0c633b0900f5da7a4a421fa731d2694";
    src = fetchgit {
      url = "https://github.com/fastai/fastai";
      rev = "a9bdde89b0c633b0900f5da7a4a421fa731d2694";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0g0znj3lgrd8kvpifsp1bwcavrpqrkjh2w4qbrzk96xrp3vf1ik7";
    };

  };
  fastcore = {
    pname = "fastcore";
    version = "51a121757e232f5f21b08d0ce7a6f7797b4585cf";
    src = fetchgit {
      url = "https://github.com/fastai/fastcore";
      rev = "51a121757e232f5f21b08d0ce7a6f7797b4585cf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "18yh7fs90m7pg3ayr1q7p7xzpvi8z36xs3wjsh7fcsxh5i825a1w";
    };

  };
  fastprogress = {
    pname = "fastprogress";
    version = "1.0.0";
    src = fetchurl {
      sha256 = "1zhv37q6jkqd1pfhlkd4yzrc3dg83vyksgzf32mjlhd5sb0qmql9";
      url = "https://pypi.io/packages/source/f/fastprogress/fastprogress-1.0.0.tar.gz";
    };

  };
  nvdtools = {
    pname = "nvdtools";
    version = "952d0696a19961ffb4bc18c415df62ea4d00d2fa";
    src = fetchgit {
      url = "https://github.com/facebookincubator/nvdtools";
      rev = "952d0696a19961ffb4bc18c415df62ea4d00d2fa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "11cki0lhmjkh6cwbckgs0hy9qspgj7czxbv5w914d1k2r62a1wcc";
    };

  };
  rmm = {
    pname = "rmm";
    version = "4d52e5c97841b7665c6c9322e082b18bb4c9dd3d";
    src = fetchgit {
      url = "https://github.com/rapidsai/rmm";
      rev = "4d52e5c97841b7665c6c9322e082b18bb4c9dd3d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "08s7bbmspyrdwmscr46p6i0nx70gzq51lz2k83jbrgzjm42sw3s3";
    };

  };
  sybilhunter = {
    pname = "sybilhunter";
    version = "2f0a8f09308f7de51ce1095353f4af82a8a15f88";
    src = fetchgit {
      url = "https://github.com/NullHypothesis/sybilhunter";
      rev = "2f0a8f09308f7de51ce1095353f4af82a8a15f88";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1gbvnalv98g366k2d0ziirqyi5psic3ga48qjdhyaslc1dns50xw";
    };

  };
  zat = {
    pname = "zat";
    version = "2924f5a713bb0c42dedbb89e031acab05b558e10";
    src = fetchgit {
      url = "https://github.com/SuperCowPowers/zat";
      rev = "2924f5a713bb0c42dedbb89e031acab05b558e10";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1k7jv07dv80cxsq1v087zb3q9li9gzxjn74lmb93xfs8sqk6lh03";
    };

  };
  zed = {
    pname = "zed";
    version = "b88d7c08a9cb5639acf729d06e35504b8975ee63";
    src = fetchgit {
      url = "https://github.com/brimdata/zed";
      rev = "b88d7c08a9cb5639acf729d06e35504b8975ee63";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1i1cksd9znw1v2njfr374ab4qnxar8ik1l50dn3jhkrq3dhiclqp";
    };

  };
}
