# nvfetcher.toml
[broker]
src.github = "zeek/broker"
fetch.github = "zeek/broker"
git.fetchSubmodules = true

[clx]
src.github = "rapidsai/clx"
fetch.github = "rapidsai/clx"

[elastalert2]
src.github = "jertel/elastalert2"
fetch.github = "jertel/elastalert2"

[choochoo]
src.git = "https://github.com/andrewcooke/choochoo"
fetch.github = "andrewcooke/choochoo"
# [cnmem]
# src.github = "NVIDIA/cnmem"
# fetch.github = "NVIDIA/cnmem"

#Python Packages
[btest]
src.pypi = "btest"
fetch.pypi = "btest"



#Go Pkgs
# [deepsea]
# src.manual= "b48e9302d079ed9f53a9123a805096a845d2c6a5"
# fetch.github = "dsnezhkov/deepsea:b48e9302d079ed9f53a9123a805096a845d2c6a5"
[zed]
src.git = "https://github.com/brimdata/zed"
fetch.github = "brimdata/zed"
