# nvfetcher.toml
[broker]
src.github = "zeek/broker"
fetch.github = "zeek/broker"
git.fetchSubmodules = true

[broker-to-json]
src.github = "grigorescu/broker-to-json"
fetch.github = "grigorescu/broker-to-json"



[eZeeKonfigurator]
src.git = "https://github.com/esnet/eZeeKonfigurator"
fetch.github = "esnet/eZeeKonfigurator"

[eZeeKonfigurator_client]
src.git = "https://github.com/esnet/eZeeKonfigurator_client"
fetch.github = "esnet/eZeeKonfigurator_client"

[clx]
src.github = "rapidsai/clx"
fetch.github = "rapidsai/clx"

[elastalert2]
src.github = "jertel/elastalert2"
fetch.github = "jertel/elastalert2"

[choochoo]
src.git = "https://github.com/andrewcooke/choochoo"
fetch.github = "andrewcooke/choochoo"

#################
# Python fastai #
#################
[fastai]
src.git = "https://github.com/fastai/fastai"
fetch.github = "fastai/fastai"

[fastcore]
src.git = "https://github.com/fastai/fastcore"
fetch.github = "fastai/fastcore"

[fastprogress]
src.pypi = "fastprogress"
fetch.pypi = "fastprogress"


# [cnmem]
# src.github = "NVIDIA/cnmem"
# fetch.github = "NVIDIA/cnmem"

#Python Packages
[btest]
src.pypi = "btest"
fetch.pypi = "btest"



#Go Pkgs
# [deepsea]
# src.manual= "b48e9302d079ed9f53a9123a805096a845d2c6a5"
# fetch.github = "dsnezhkov/deepsea:b48e9302d079ed9f53a9123a805096a845d2c6a5"
[zed]
src.git = "https://github.com/brimdata/zed"
fetch.github = "brimdata/zed"

[nvdtools]
src.git = "https://github.com/facebookincubator/nvdtools"
fetch.github = "facebookincubator/nvdtools"
